### ISSUE TITLE
GetChaosContainerStatus is always loop

### ISSUE THREAD

**Issue by pengwenwu** [litmuschaos/chaos-runner#207]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

**What happened**:
When using the cnf-test test suite to execute the node_drain test case, use the chaos-runner image of v2.14.0. isCompleted is always false when the GetChaosContainerStatus method is executed.
if container.State.Terminated.Reason == "Completed" {
isCompleted = !container.Ready
}
The judgment is incorrect. When the job is complete, isCompleted = container.Ready is displayed.

**What you expected to happen**:
The execution ends normally, instead of an infinite loop.

**How to reproduce it (as minimally and precisely as possible)**:
isCompleted = container.Ready

**Anything else we need to know?**:

**Comment by neelanjan00** [comment]
This code is no longer valid, we have updated this as part of the latest releases. Thanks for the issue!

**Comment by neelanjan00** [comment]
If you have any further doubt, feel free to open another issue!
