### ISSUE TITLE
Refactor runner.go in compliance with BCH 

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/chaos-runner#54]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by neelanjan00** [comment]
This is completed, thanks for the issue!
